const categoryByLayer = {
  "Academic Buildings": "Academic Building",
  "Athletics": "Athletics",
  "Campus Services": "Campus Service",
  "Dining and Student Life": "Dining / Student Life",
  "Former / Inactive Housing": "Former / Inactive Housing",
  "Housing": "Housing",
  "Landmarks": "Campus Landmark",
  "Parking and Transportation": "Parking / Transportation"
};

const locations = [
  ["Band and Music Hall", "Academic Buildings", 35.2449048, -80.8561284, "Music, band, rehearsal, and arts-related academic space.", "band music rehearsal instruments arts performance"],
  ["Dorothy Cowser Yancy Technology Center", "Academic Buildings", 35.2419873, -80.8572047, "Technology-focused academic building with classrooms, computer labs, and digital learning spaces.", "technology computer lab computers IT digital learning classrooms"],
  ["George E. Davis Hall", "Academic Buildings", 35.2421828, -80.8570009, "Academic building connected to classroom, student support, and technology functions.", "davis hall classrooms academic student support technology"],
  ["Henry Lawrence McCrorey Memorial Hall", "Academic Buildings", 35.2427717, -80.8558348, "Academic building with classroom, office, and social science-related spaces.", "mccrorey mcrorey social science classrooms theology"],
  ["Irwin Belk Complex", "Academic Buildings", 35.2416921, -80.853052, "Athletic and academic facility for football, track, classes, and Health and Human Performance spaces.", "irwin belk football track classes athletics stadium HHP"],
  ["James B. Duke Memorial Library", "Academic Buildings", 35.2431047, -80.8572703, "Central academic resource for studying, research, printing, technology access, archives, and group study.", "library study books research printing archives"],
  ["Lionel H. Newsom Humanities Hall", "Academic Buildings", 35.2429027, -80.85534, "Humanities academic building with classrooms, offices, and student learning spaces.", "newsom humanities classrooms language lab lecture hall"],
  ["Metropolitan College", "Academic Buildings", 35.2423989, -80.8560069, "Academic and campus services building for Metropolitan College and adult, evening, online, and support programs.", "metropolitan college albright adult degree online evening veteran single stop"],
  ["New Science Center (STEM)", "Academic Buildings", 35.2422429, -80.8574075, "STEM facility with classrooms, teaching labs, faculty offices, and science learning spaces.", "science STEM biology chemistry labs research classrooms"],
  ["Old Science Building", "Academic Buildings", 35.2422217, -80.8567024, "Former science-related academic building; current use should be verified.", "old science former science academic classrooms labs"],
  ["Rufus R. Perry Hall", "Academic Buildings", 35.242401, -80.8567025, "Academic building connected in campus references with George E. Davis Hall.", "perry hall davis classrooms academic faculty offices"],
  ["Sustainability Village (Aquaponics Garden)", "Academic Buildings", 35.2435007, -80.8534333, "Outdoor learning space focused on aquaponics, food systems, sustainability, and environmental education.", "sustainability aquaponics garden outdoor learning food systems"],
  ["Sustainability Village (Community Garden)", "Academic Buildings", 35.2432534, -80.8535781, "Outdoor campus garden space connected to sustainability, food access, wellness, and community engagement.", "sustainability community garden outdoor learning food access wellness"],
  ["William F. Johnson & James W. Seabrook Hall", "Academic Buildings", 35.2418543, -80.855917, "Academic building supporting education, business, communication arts, and classroom activity.", "johnson seabrook education business communication arts classrooms"],
  ["Athletic Support Hall", "Athletics", 35.242707, -80.8534308, "Athletics support building for sports administration, team support, and related services.", "athletic support athletics office coaches teams"],
  ["Basketball Court #1", "Athletics", 35.2438037, -80.8545822, "Outdoor basketball court for recreation, practice, and student activity.", "basketball court outdoor recreation athletics"],
  ["Basketball Court #2", "Athletics", 35.2433548, -80.8591884, "Outdoor basketball court for recreation, practice, and student activity.", "basketball court outdoor recreation athletics"],
  ["Jack S. Brayboy Gymnasium", "Athletics", 35.2428631, -80.8544711, "Indoor athletic facility for basketball, recreation, physical education, campus events, and athletics.", "brayboy gym gymnasium basketball athletics events"],
  ["Jack S. Brayboy HealthPlex", "Athletics", 35.2427885, -80.8539859, "Fitness and wellness facility connected to exercise, recreation, and health-related activity.", "healthplex fitness wellness gym workout exercise"],
  ["Student Athlete Achievement Center", "Athletics", 35.2433713, -80.852759, "Student-athlete support space for academic success, advising, studying, and athletic department support.", "student athlete achievement academic support advising athletics"],
  ["Tennis Court", "Athletics", 35.2442725, -80.8544534, "Outdoor tennis and recreation space.", "tennis court outdoor recreation athletics"],
  ["Track and Field (Throwers)", "Athletics", 35.244922, -80.8538285, "Track and field throws area for athletic practice and events.", "track field throwers shot put discus athletics"],
  ["Administrative Cottage #1 (Custodial)", "Campus Services", 35.2453412, -80.8567965, "Campus services cottage connected to custodial or administrative operations.", "administrative cottage custodial campus services"],
  ["Administrative Cottage #2 (Facilities)", "Campus Services", 35.24549, -80.8567858, "Campus services cottage connected to facilities or administrative operations.", "administrative cottage facilities maintenance campus services"],
  ["Administrative Cottage #3 (Counseling Center)", "Campus Services", 35.244772, -80.8578928, "Campus services cottage connected to counseling or student support services.", "administrative cottage counseling center student support"],
  ["Administrative Cottage #4 (Campus Police)", "Campus Services", 35.2435077, -80.8552996, "Campus safety location for security, emergency response, and public safety support.", "campus police security public safety emergency"],
  ["Administrative Cottage #5 (Faculty Hall)", "Campus Services", 35.241994, -80.8550484, "Faculty and campus support building used for offices, meetings, and university functions.", "faculty hall faculty offices staff meetings"],
  ["Andrew Carnegie Hall", "Campus Services", 35.2428315, -80.8566423, "Academic support and career development building connected to the Smith Institute.", "carnegie hall smith institute career development research postgraduate"],
  ["Edward Crutchfield Cottage", "Campus Services", 35.2417373, -80.8552376, "Administrative campus cottage used for university office functions.", "crutchfield cottage edward crutchfield administration"],
  ["George E. Davis Cottage", "Campus Services", 35.2447647, -80.8587293, "Campus cottage used for university office or auxiliary functions.", "george davis cottage administrative auxiliary office"],
  ["Henry J. Biddle Hall", "Campus Services", 35.2435353, -80.8568749, "Includes Admissions, Financial Aid, Student Accounts, Housing Support, and the Campus Pantry.", "biddle admissions financial aid student accounts housing pantry"],
  ["JCSU Health Center", "Campus Services", 35.2437986, -80.8566022, "Student health service located inside the Mary Joyce Taylor Crisp Memorial Student Union.", "health center clinic doctor nurse wellness medical care"],
  ["Johnson C. Smith Cottage (Human Resources)", "Campus Services", 35.2421504, -80.8560453, "Administrative building that houses Human Resources.", "human resources HR employment campus jobs work-study"],
  ["University Auxiliary Hall #1 (EHSC High School)", "Campus Services", 35.2462352, -80.8549456, "Auxiliary campus building associated with EHSC High School.", "auxiliary hall EHSC high school partner school"],
  ["Violet Washington Cottage", "Campus Services", 35.244899, -80.8577936, "Campus cottage used for university office or auxiliary functions.", "violet washington cottage administrative auxiliary office"],
  ["Cafeteria", "Dining and Student Life", 35.2437796, -80.8562033, "Main campus dining location for meals, gathering, and meal plan services.", "cafeteria dining food meals meal plan"],
  ["KoKoMo's Coffeehouse", "Dining and Student Life", 35.2434115, -80.8572086, "Campus coffee and gathering location for snacks, studying, meetings, and social time.", "kokomo coffee coffeehouse snacks study cafe"],
  ["Mary Joyce Taylor Crisp Memorial Student Union", "Dining and Student Life", 35.2436004, -80.8560014, "Student life building with Grimes Lounge, Lorraine's, Bull Pen, Pizza Hut, Bookstore, dining, and gathering spaces.", "student union grimes lorraine bull pen pizza hut bookstore"],
  ["The Block", "Dining and Student Life", 35.2435255, -80.8564366, "Student-known campus area used as a common reference point, hangout spot, and meeting location.", "block hangout meeting spot landmark student life"],
  ["Hardy Liston Hall", "Former / Inactive Housing", 35.2439102, -80.8585233, "Historically listed as a residence hall; current student housing status should be verified.", "liston hall former inactive dorm housing"],
  ["James H. and Jane M. Berry Hall", "Former / Inactive Housing", 35.2451056, -80.8567475, "Historically listed as a residence hall; current use should be verified.", "berry hall former inactive dorm housing"],
  ["Johnson C. Smith Memorial Hall", "Former / Inactive Housing", 35.2431614, -80.8562579, "Former residence hall now associated with office, facilities, or student support space.", "smith memorial hall former dorm office facilities"],
  ["Hartley Wood Hall", "Housing", 35.2452333, -80.8560886, "Campus building listed in the housing layer; verify whether it is active housing or arts/event space.", "hartley wood woods hall housing verify"],
  ["James B. Duke Memorial Hall", "Housing", 35.2441251, -80.8590338, "Residence hall connected to student housing and campus living.", "duke hall dorm residence housing honors"],
  ["Mary A. Carter Hall", "Housing", 35.2443682, -80.8561385, "Residence hall connected to student housing and campus living.", "carter hall dorm residence housing"],
  ["Mosaic Village", "Housing", 35.2396087, -80.8587225, "Student apartment and mixed-use housing complex.", "mosaic village housing apartments student apartments"],
  ["Myers Hall", "Housing", 35.2445983, -80.8570225, "Active freshman male residence hall used for student housing and Residence Life navigation.", "myers dorm housing freshman residence"],
  ["New Residence Hall", "Housing", 35.2448625, -80.8550468, "Suite-style residence hall connected to student housing and campus living.", "new residence hall dorm housing suites"],
  ["Sanders Hall", "Housing", 35.2443937, -80.8586631, "Residence hall connected to student housing and campus living.", "sanders hall dorm housing freshman residence"],
  ["Wilbert Greenfield Residence Hall", "Housing", 35.2442821, -80.855477, "Active freshman female residence hall used for student housing and Residence Life navigation.", "greenfield dorm housing freshman female residence"],
  ["Jane M. Smith Hall (Chapel)", "Landmarks", 35.2419091, -80.8575869, "Campus chapel, religious life, event space, and navigation landmark.", "chapel church memorial religious life events landmark"],
  ["Old Central Steam Plant", "Landmarks", 35.2435012, -80.8549214, "Historic campus utility building and recognizable landmark.", "old central steam plant utility facilities landmark"],
  ["Physical Plant #2", "Landmarks", 35.2418302, -80.8567188, "Facilities building used for maintenance, operations, and physical plant support.", "physical plant facilities maintenance operations"],
  ["Physical Plant #3", "Landmarks", 35.2419565, -80.856696, "Facilities building used for maintenance, operations, and physical plant support.", "physical plant facilities maintenance operations"],
  ["Entrance #1", "Parking and Transportation", 35.2445557, -80.8575333, "Campus entry point used for driving, walking, and wayfinding.", "entrance campus entrance gate access directions"],
  ["Entrance #2", "Parking and Transportation", 35.2433066, -80.8580289, "Campus entry point used for driving, walking, and wayfinding.", "entrance campus entrance gate access directions"],
  ["Faculty Parking", "Parking and Transportation", 35.2416077, -80.8555508, "Faculty and staff parking area; permit or decal may be required.", "faculty parking staff parking permit decal"],
  ["Faculty Parking", "Parking and Transportation", 35.2424072, -80.8553327, "Faculty and staff parking area; permit or decal may be required.", "faculty parking staff parking permit decal"],
  ["Faculty Parking", "Parking and Transportation", 35.2416051, -80.8570855, "Faculty and staff parking area; permit or decal may be required.", "faculty parking staff parking permit decal"],
  ["Faculty Parking", "Parking and Transportation", 35.2415435, -80.8559616, "Faculty and staff parking area; permit or decal may be required.", "faculty parking staff parking permit decal"],
  ["Faculty Parking", "Parking and Transportation", 35.2423836, -80.8579673, "Faculty and staff parking area; permit or decal may be required.", "faculty parking staff parking permit decal"],
  ["Faculty Parking", "Parking and Transportation", 35.2418184, -80.8565133, "Faculty and staff parking area; permit or decal may be required.", "faculty parking staff parking permit decal"],
  ["Faculty/Student Parking", "Parking and Transportation", 35.243703, -80.8591722, "Shared parking area for students, faculty, or staff with proper authorization.", "faculty student parking shared parking permit decal"],
  ["Public Parking", "Parking and Transportation", 35.2448025, -80.8590441, "Public or visitor parking area; visitors should check signs and campus rules.", "public parking visitor parking guest parking"],
  ["Public Parking", "Parking and Transportation", 35.2421613, -80.8543043, "Public or visitor parking area; visitors should check signs and campus rules.", "public parking visitor parking guest parking"],
  ["Student Parking", "Parking and Transportation", 35.2450371, -80.8557988, "Student parking area; permit or decal may be required.", "student parking commuter parking permit decal"],
  ["Student Parking", "Parking and Transportation", 35.2443228, -80.8591782, "Student parking area; permit or decal may be required.", "student parking commuter parking permit decal"],
  ["Student Parking", "Parking and Transportation", 35.2455213, -80.854893, "Student parking area; permit or decal may be required.", "student parking commuter parking permit decal"]
].map(([name, layer, lat, lng, description, keywordText]) => ({
  name,
  layer,
  category: categoryByLayer[layer] || layer,
  description,
  keywords: keywordText.split(" "),
  lat,
  lng
}));
